# Generated by Django 5.1.7 on 2025-03-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_alter_film_image_favorit'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
