# Generated by Django 5.1.7 on 2025-03-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_film_trailer_url_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='trailer_url',
        ),
    ]
