# Generated by Django 5.1.7 on 2025-03-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_movie_remove_film_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.TextField(default='Kein Film verfügbar'),
        ),
    ]
