# Generated by Django 5.1.7 on 2025-03-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_movie_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.URLField(default='Kein Film verfügbar'),
        ),
    ]
