# Generated by Django 5.1.7 on 2025-03-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_alter_movie_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
