# Generated by Django 5.1.7 on 2025-04-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_profile_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
