# Generated by Django 5.1.7 on 2025-04-20 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0015_movie_release_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='kommentar',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='kommentar',
            old_name='datum',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='kommentar',
            name='autor',
        ),
        migrations.AddField(
            model_name='kommentar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
